// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agbytqnodmqtkboklotu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnYnl0cW5vZG1xdGtib2tsb3R1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NjIwNjYsImV4cCI6MjA3MjEzODA2Nn0.JQbkrdzLaPPAGg4UIz-U7_hK2-tB9WBzrxLwgx4uG3U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});